package main.java.form;

import main.java.Main;
import main.java.model.UserModel;

public class CashierFrame extends javax.swing.JFrame {

    public CashierFrame() {
        initComponents();
        this.setIconImage(
            new javax.swing.ImageIcon(getClass().getResource(
                            "/main/resources/images/RLogo-small.png"))
                    .getImage());
    }
    
    public void setUser(UserModel user) {
        this.currentUser = user;
        this.usernameLabel.setText(user.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel headerPanel = new javax.swing.JPanel();
        javax.swing.JLabel title = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        javax.swing.JLabel usernameDescLabel = new javax.swing.JLabel();
        javax.swing.JSeparator seperator = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        createBillMenuButton = new javax.swing.JToggleButton();
        productInfoMenuButton = new javax.swing.JToggleButton();
        salesStatsMenuButton = new javax.swing.JToggleButton();
        billPanel = new main.java.form.BillPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPOS System");

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/RLogo-small.png"))); // NOI18N
        title.setText("RPOS System");

        usernameLabel.setText("username");
        usernameLabel.setToolTipText("");

        usernameDescLabel.setForeground(new java.awt.Color(181, 181, 181));
        usernameDescLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/user.png"))); // NOI18N
        usernameDescLabel.setLabelFor(usernameLabel);
        usernameDescLabel.setText("signed in as");

        seperator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/logout.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/dialog-question.png"))); // NOI18N
        infoButton.setText("info");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        menuButtons.add(createBillMenuButton);
        createBillMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/bill.png"))); // NOI18N
        createBillMenuButton.setSelected(true);
        createBillMenuButton.setText("Create Bill");
        createBillMenuButton.setBorderPainted(false);
        createBillMenuButton.setFocusPainted(false);

        menuButtons.add(productInfoMenuButton);
        productInfoMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/accessories-dictionary.png"))); // NOI18N
        productInfoMenuButton.setText("Product Info");
        productInfoMenuButton.setToolTipText("Not Implemented Yet");
        productInfoMenuButton.setBorderPainted(false);
        productInfoMenuButton.setEnabled(false);
        productInfoMenuButton.setFocusPainted(false);

        menuButtons.add(salesStatsMenuButton);
        salesStatsMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/stock.png"))); // NOI18N
        salesStatsMenuButton.setText("Sales Stats");
        salesStatsMenuButton.setToolTipText("Not Implemented Yet");
        salesStatsMenuButton.setBorderPainted(false);
        salesStatsMenuButton.setEnabled(false);
        salesStatsMenuButton.setFocusPainted(false);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(createBillMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productInfoMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesStatsMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addGap(6, 6, 6)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(usernameDescLabel)
                    .addComponent(usernameLabel)
                    .addComponent(logoutButton)
                    .addComponent(infoButton)
                    .addComponent(createBillMenuButton)
                    .addComponent(productInfoMenuButton)
                    .addComponent(salesStatsMenuButton))
                .addContainerGap())
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seperator))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(billPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        currentUser = null;
        Main.showLoginFrame();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        new InfoDialog(this).setVisible(true);
    }//GEN-LAST:event_infoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.java.form.BillPanel billPanel;
    private javax.swing.JToggleButton createBillMenuButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JToggleButton productInfoMenuButton;
    private javax.swing.JToggleButton salesStatsMenuButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
    private final javax.swing.ButtonGroup menuButtons =
            new javax.swing.ButtonGroup();
    
    private UserModel currentUser = null;
}
